In [1]:
import numpy as np

In [2]:
a = np.array([
    [1, 2],
    [4, 5],
    [8, 9],
    [12, 1],
    [5, 2]
])

id = np.where(a[:, 0] > 5)[0]
id

array([2, 3], dtype=int64)

In [3]:
a = np.delete(a, id, axis=0)
a

array([[1, 2],
       [4, 5],
       [5, 2]])

In [4]:
arr = np.array([True, True, False, True, False])

old_to_new = np.logical_not(arr).cumsum() - 1
old_to_new

array([-1, -1,  0,  0,  1])

In [6]:
import pickle

from utils.map import Map

with open('saves\sim_t_1_T0_298.15_v0_1000_dsty_0.03_rltmass_2.88e+01\keyframes_00.pkl', 'rb') as f:
    keyframes = pickle.load(f)

In [7]:
keyframes

[{'t': 0.4990000000000004,
  'ptcl_pos': array([[7.8867194e+02, 5.9828192e+02],
         [8.7472510e+02, 5.2725024e+02],
         [8.8704114e+02, 6.2204883e+02],
         ...,
         [9.2258519e-01, 3.6398260e+02],
         [8.1151438e-01, 2.9995517e+02],
         [9.4939548e-01, 3.1370416e+02]], dtype=float32),
  'ptcl_v': array([[1098.7817  ,  130.2403  ],
         [ 800.66364 ,   58.892853],
         [1129.5916  ,  441.42636 ],
         ...,
         [ 922.58514 , -463.24536 ],
         [1005.62213 , -435.3318  ],
         [ 949.39545 , -253.0786  ]], dtype=float32)},
 {'t': 0.5010000000000003,
  'ptcl_pos': array([[ 7.9086945e+02,  5.9854242e+02],
         [ 8.7705872e+02,  5.2837170e+02],
         [ 8.8930029e+02,  6.2293164e+02],
         ...,
         [ 1.4980190e+00,  2.4948163e+02],
         [ 1.3702908e+00,  3.2657224e+02],
         [-2.1357584e-01,  4.1945605e+02]], dtype=float32),
  'ptcl_v': array([[ 1.0987817e+03,  1.3024030e+02],
         [ 1.3517257e+03,  8.1417163e+0

In [8]:
from utils.visualize import make_video

make_video(keyframes)

Generating video frames...
Total frames number: 499


499it [01:56,  4.28it/s]


Video saved at ./saves\test\output_00.mp4
